<?php
session_start();
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') { header('Location: login.php'); exit; }
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rubrik Penilaian Alternatif</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="includes/admin.css"></head>
<?php include __DIR__.'/includes/admin_header.php'; ?>
<div class="container py-4">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h3 class="fw-bold mb-1">Rubrik Penilaian Alternatif</h3><p class="text-muted mb-0">Pedoman agar nilai nama tidak diberikan secara acak.</p></div><a href="admin_dashboard.php" class="btn btn-outline-secondary">Dashboard</a></div>
<div class="alert alert-info"><strong>Penting:</strong> Skor 1–9 pada alternatif <b>bukan Skala Saaty</b>. Skor ini adalah nilai alternatif berdasarkan rubrik. Skala Saaty hanya digunakan ketika pengguna menentukan prioritas antar kriteria.</div>
<div class="row g-4">
<div class="col-lg-4"><div class="card h-100 shadow-sm"><div class="card-header bg-success text-white fw-bold">C1 — Arti Nama</div><div class="card-body"><table class="table table-sm"><tr><th>Skor</th><th>Pedoman</th></tr><tr><td>9</td><td>Sangat baik: makna sangat positif dan kuat.</td></tr><tr><td>7</td><td>Baik: makna positif dan jelas.</td></tr><tr><td>5</td><td>Cukup: makna positif tetapi umum.</td></tr><tr><td>3</td><td>Kurang: makna positifnya terbatas.</td></tr><tr><td>1</td><td>Tidak sesuai: makna kurang baik/tidak sesuai.</td></tr></table><p class="small text-muted mb-0">Dasar isi arti: buku/referensi nama yang digunakan dalam penelitian.</p></div></div></div>
<div class="col-lg-4"><div class="card h-100 shadow-sm"><div class="card-header bg-success text-white fw-bold">C2 — Tingkat Keunikan</div><div class="card-body"><table class="table table-sm"><tr><th>Skor</th><th>Pedoman</th></tr><tr><td>9</td><td>Sangat unik</td></tr><tr><td>5</td><td>Sedang</td></tr><tr><td>1</td><td>Umum</td></tr></table><p class="small text-muted">Kategori keunikan harus ditetapkan dari dataset penelitian, misalnya berdasarkan frekuensi kemunculan nama. Jangan menilai berdasarkan selera pribadi.</p></div></div></div>
<div class="col-lg-4"><div class="card h-100 shadow-sm"><div class="card-header bg-success text-white fw-bold">C3 — Nilai Keislaman</div><div class="card-body"><table class="table table-sm"><tr><th>Skor</th><th>Pedoman</th></tr><tr><td>9</td><td>Asmaul Husna / Nabi</td></tr><tr><td>8</td><td>Sahabat / Tokoh Mulia</td></tr><tr><td>7</td><td>Bahasa Arab bermakna baik</td></tr><tr><td>5</td><td>Nama lokal positif</td></tr><tr><td>3</td><td>Kategori lain yang belum memenuhi indikator di atas</td></tr></table><p class="small text-muted mb-0">Kategori harus memiliki dasar dari karakteristik nama dan sumber yang dipakai dalam penelitian.</p></div></div></div>
</div>
<div class="card shadow-sm mt-4"><div class="card-body"><h5 class="fw-bold">Yang perlu dicantumkan di skripsi</h5><ol class="mb-0"><li>Sumber buku/referensi yang digunakan untuk data nama dan arti.</li><li>Indikator dan rubrik penilaian setiap kriteria.</li><li>Penjelasan bahwa skor alternatif berbeda dengan Skala Saaty.</li><li>Untuk C2, jelaskan dasar penentuan kategori keunikan dari dataset.</li></ol></div></div>
</div><?php include __DIR__.'/includes/admin_footer.php'; ?></html>
